export const GET_COVID = 'GET_COVID';
export const GET_MATRIX_DATA = 'GET_MATRIX_DATA';
export const GET_REGRESSION = 'GET_REGRESSION';
export const GET_MACHINE_LEARNING_DATA = 'GET_MACHINE_LEARNING_DATA';
