export const GET_COVID = 'GET_COVID';
export const GET_COVID_RUSSIA = 'GET_COVID_RUSSIA';
export const GET_MATRIX_DATA = 'GET_MATRIX_DATA';
export const GET_REGRESSION = 'GET_REGRESSION';
export const GET_MACHINE_LEARNING = 'GET_MACHINE_LEARNING';
