export const GET_COVID = 'GET_COVID';
export const GET_MATRIX_DATA = 'GET_MATRIX_DATA';
export const GET_REGRESSION = 'GET_REGRESSION';
export const GET_SVM_DATA = 'GET_SVM_DATA';
export const GET_RANDOM_FOREST_DATA = 'GET_RANDOM_FOREST_DATA';
